### ISSUE TITLE
请问可否增加对 vsys 系统信息 的配置项

### ISSUE THREAD

**Issue by pengye91** [xCss/Valine#120]
请问可否增加对 vsys 系统信息 的配置项

**Comment by xCss** [comment]
可以自定义css
``` css
.vsys{display:none;}
```
