### ISSUE TITLE
Hexo 主题 无法提供访问统计

### ISSUE THREAD

**Issue by xiongyizhu** [xCss/Valine#137]
### 应用无法自动创建类Counter，而自己手动创建的不知道字段是什么
```
<div id="<%= post.path %>"  class="leancloud-visitors" data-flag-title=" <%= post.title %>">
    <span class="has-text-grey">
            阅读量: <span class="leancloud-visitors-count">0</span>
    </span>
</div>
```
>配置文件
```
comment:
    # https://valine.js.org/visitor.html
    type: valine
    app_id: wPr1GNWRMj1g1hsOJJjSVmV2-gzGzoHsz        # (required) LeanCloud application id
    app_key: k9TscdDiJKXGV1KSBX71D4Jm                # (required) LeanCloud application key
    notify: true                                     # (optional) receive email notification
    verify: false                                    # (optional) show verification code
    placeholder: 快来留个言吧！                       # (optional) comment box placeholder text
    visitor: true                                    # 文章访问量统计
    avatar: wavatar                                  # 随机头像组成
```

>ejs文件:
```
<% if (!has_config('comment.app_id') || !has_config('comment.app_key')) { %>
<div class="notification is-danger">
    You forgot to set the <code>app_id</code> or <code>app_key</code> for Valine. Please set it in <code>_config.yml</code>.
</div>
<% } else { %>
<div id="valine-thread"></div>
<script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>
<script src='//unpkg.com/valine/dist/Valine.min.js'></script>
<script>
    new Valine({
        el: '#valine-thread' ,
        notify: <%= get_config('comment.notify') %>,
        verify: <%= get_config('comment.verify') %>,
        app_id: '<%= get_config('comment.app_id') %>',
        app_key: '<%= get_config('comment.app_key') %>',
        placeholder: '<%= get_config('comment.placeholder') %>',
        avatar: '<%= get_config('comment.avatar') %>',
        visitor: true
    });
</script>
<% } %>
```
