### ISSUE TITLE
评论数为0

### ISSUE THREAD

**Issue by xieqing0428** [xCss/Valine#181]
https://alessa0.cn
里面已经有评论了 但是评论数还是显示为0,无论首页还是文章页, leancloud访问数倒是正常
hexo: 3.8.0
hexo-theme-next(version: "7.1.0")
``` 
valine:
  enable: true
  appid: ***
  appkey: ***
  notify: true
  verify: true
  placeholder: Just go go
  avatar: mm
  guest_info: nick,mail,link
  pageSize: 10
  language: zh-cn
  visitor: false
  comment_count: true

leancloud_visitors:
  enable: true
  app_id: ***
  app_key: ***
  security: true
  betterPerformance: true
```
