### ISSUE TITLE
提个反人类的问题

### ISSUE THREAD

**Issue by vxhly** [xCss/Valine#20]
`_config.yml`

```yml
valine:
  notify: true
  verify: false
```

我的配置如上，只开启了邮箱提醒不开启验证码验证，然后会默认开启验证码，嗯~ o(*￣▽￣*)o，对于算术验证这种反人类的验证我是不喜欢的，楼主可以添加其他验证方法，比如滑块的验证，字母数字组合验证
