### ISSUE TITLE
客户端系统主题是暗色模式时，Valine 组件很难看清

### ISSUE THREAD

**Issue by real-neo** [xCss/Valine#221]
在 macOS 与 Android 暗色下都会遇到此问题：
![截屏2019-11-2422 17 37](https://user-images.githubusercontent.com/11043462/69496007-534e0b00-0f08-11ea-9c9a-ea21ce300511.png)

我个人修改的办法是添加如下代码：
``` css
    @media (prefers-color-scheme: dark) {
        .v a,
        .v p
        {color: #fff;}
    }
```
![截屏2019-11-2422 17 50](https://user-images.githubusercontent.com/11043462/69496011-5b0daf80-0f08-11ea-8826-d99424518ce1.png)

希望可以改进暗色模式下的可阅读性。

**Comment by real-neo** [comment]
上面这个不是很完善，没有考虑到 at 链接和 placeholder 等等，这个更完善
``` css
    @media (prefers-color-scheme: dark) {
        .v *,
        .v .vwrap input,
        .v .vwrap input::placeholder,
        .v .veditor,
        .v .veditor::placeholder,
        .v a,
        .v a:hover {
            color: hsla(0,0%,100%,.75);
            opacity: 1;
        }
        .v .vbtn {
            color: hsla(0,0%,100%,.75);
            background: #333;
            border: none;
        }
        .v .vbtn:hover {
            color: #3090e4;
            border-color: #3090e4;
        }
        .v .vlist .vcard .vhead .vsys {
            background: #333;
        }
```

**Comment by jerryc127** [comment]
这个靠自己去适配了
比如代码块那些

都要去调

**Comment by stevenjoezhang** [comment]
"Click on expand" 的透明度渐变效果也只在浅色背景下有效
https://github.com/xCss/Valine/blob/d4ec8c41bad316b02d2002c3e1be4bad7a90eb46/src/index.scss#L449
<img width="365" alt="截屏2020-03-30 上午12 17 01" src="https://user-images.githubusercontent.com/16272760/77854280-fe0a6900-721b-11ea-88ba-98186a6d0f09.png">

**Comment by real-neo** [comment]
> "Click on expand" 的透明度渐变效果也只在浅色背景下有效
> https://github.com/xCss/Valine/blob/d4ec8c41bad316b02d2002c3e1be4bad7a90eb46/src/index.scss#L449
> 
> 
> <img alt="截屏2020-03-30 上午12 17 01" width="365" src="https://user-images.githubusercontent.com/16272760/77854280-fe0a6900-721b-11ea-88ba-98186a6d0f09.png">

可以参考我的简略代码：
``` css
    .v .vlist .vcard .vcontent.expand:before {
        background: linear-gradient(180deg,hsla(0,0%,20%,0),hsla(0, 0%, 20%, 0.9));
    }
    .v .vlist .vcard .vcontent.expand:after {
        background: hsla(0, 0%, 20%, 0.9);
    }
```

https://realneo.me/temp-fix-valine-in-dark/
