### ISSUE TITLE
邮件提醒功能并未正常工作

### ISSUE THREAD

**Issue by hiberabyss** [xCss/Valine#27]
Hi，我在 `_config.yml` 里使用了下面的配置，发现当 blog 里有新的 comment 时并未收到邮件提醒。

```
valine:
  enable: true ## if you want to use Valine comment system, please set the value to true
  appid: myappid ## your leancloud application appid
  appkey: myappkey ## your leancloud application appkey
  notify: true ## mail notifier , https://github.com/xCss/Valine/wiki
  verify: true ## Verification code
  placeholder: Just go go ## comment input placeholder text 
  avatar: 'wavatar' ## header image https://github.com/xCss/Valine/wiki
  pageSize: 10 ## 
  guest_info: nick,mail
```

Thanks！
