### ISSUE TITLE
Code -1: Request has been terminated Possible causes: the network is offline

### ISSUE THREAD

**Issue by meteorsh** [xCss/Valine#322]
我这几天看我博客valine 评论系统，突然变成这样了，我没有进行过其他设置，不知道为什么会这样？
![image](https://user-images.githubusercontent.com/46078304/82977520-b4b87900-a014-11ea-85e3-a0a887630a52.png)

我的配置如下：
```
valine:
  enable: true
  appId: IxCmL0inFVNR357gq7byXEqE-9Nh9j0Va
  appKey: 8T47xkadi7qnTGxEnvLqWAhE
  notify: true
  verify: false
  visitor: true
  avatar: 'wavatar' # https://valine.js.org/avatar.html Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  pageSize: 10
  placeholder: 'just go go' # Comment Box placeholder
  background: /medias/comment_bg.pn
```
