### ISSUE TITLE
LeanCloud未能自动生成Comment Class

### ISSUE THREAD

**Issue by Ahaochan** [xCss/Valine#75]
OS: windows 10
Brower: Chrome 63.0.3239.108
我阅读了[快速开始](https://valine.js.org/quickstart/#_3), 并将其应用在了Hexo的[NexT主题](https://github.com/theme-next/hexo-theme-next)上.
当我部署之后, 我在LeanCloud没有发现[快速开始](https://valine.js.org/quickstart/#_3)中提到的`Comment Class`.

1. 是否需要自己手动创建`Comment Class`?
2. `Comment Class`中应该包含哪些字段?

![image](https://user-images.githubusercontent.com/17980786/38992165-7a029a3a-4412-11e8-8634-76cb8c0af46a.png)
```yml
valine:
  enable: true
  appid: ********
  appkey: ********
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: 酷爱来写下你的评论吧👿
  avatar: retro # gravatar style
  guest_info: nick,mail # custom comment header
  pageSize: 10 # pagination size
```
